#ifndef MOS_AGONDEV_LOWERCASE_EZ80_H
#define MOS_AGONDEV_LOWERCASE_EZ80_H

#include <ez80f92.h>

/*
 * AgonDev exposes peripheral names as numeric addresses.  ZDS exposes the
 * same names as volatile byte lvalues.  Snapshot only the registers used by
 * agon-mos before replacing those names with AgonDev address-space I/O.
 * Numeric constants (vectors, reset values, and pin masks) continue to come
 * directly from the official AgonDev header.
 */
enum {
    MOS_AGONDEV_ADDR_TMR0_CTL = TMR0_CTL,
    MOS_AGONDEV_ADDR_TMR0_DR_L = TMR0_DR_L,
    MOS_AGONDEV_ADDR_TMR0_RR_L = TMR0_RR_L,
    MOS_AGONDEV_ADDR_TMR0_DR_H = TMR0_DR_H,
    MOS_AGONDEV_ADDR_TMR0_RR_H = TMR0_RR_H,
    MOS_AGONDEV_ADDR_PC_DR = PC_DR,
    MOS_AGONDEV_ADDR_PC_DDR = PC_DDR,
    MOS_AGONDEV_ADDR_PC_ALT1 = PC_ALT1,
    MOS_AGONDEV_ADDR_PC_ALT2 = PC_ALT2,
    MOS_AGONDEV_ADDR_PD_DR = PD_DR,
    MOS_AGONDEV_ADDR_PD_DDR = PD_DDR,
    MOS_AGONDEV_ADDR_PD_ALT1 = PD_ALT1,
    MOS_AGONDEV_ADDR_PD_ALT2 = PD_ALT2,
    MOS_AGONDEV_ADDR_UART0_BRG_L = UART0_BRG_L,
    MOS_AGONDEV_ADDR_UART0_IER = UART0_IER,
    MOS_AGONDEV_ADDR_UART0_BRG_H = UART0_BRG_H,
    MOS_AGONDEV_ADDR_UART0_FCTL = UART0_FCTL,
    MOS_AGONDEV_ADDR_UART0_LCTL = UART0_LCTL,
    MOS_AGONDEV_ADDR_UART0_MCTL = UART0_MCTL,
    MOS_AGONDEV_ADDR_I2C_CTL = I2C_CTL,
    MOS_AGONDEV_ADDR_I2C_CCR = I2C_CCR,
    MOS_AGONDEV_ADDR_UART1_BRG_L = UART1_BRG_L,
    MOS_AGONDEV_ADDR_UART1_IER = UART1_IER,
    MOS_AGONDEV_ADDR_UART1_BRG_H = UART1_BRG_H,
    MOS_AGONDEV_ADDR_UART1_FCTL = UART1_FCTL,
    MOS_AGONDEV_ADDR_UART1_LCTL = UART1_LCTL,
    MOS_AGONDEV_ADDR_UART1_MCTL = UART1_MCTL,
    MOS_AGONDEV_ADDR_CLK_PPD1 = CLK_PPD1,
};

#define MOS_AGONDEV_ASSERT_REGISTER(name, address) \
    _Static_assert(MOS_AGONDEV_ADDR_##name == (address), \
                   "AgonDev register address changed: " #name)

MOS_AGONDEV_ASSERT_REGISTER(TMR0_CTL, 0x80);
MOS_AGONDEV_ASSERT_REGISTER(TMR0_DR_L, 0x81);
MOS_AGONDEV_ASSERT_REGISTER(TMR0_RR_L, 0x81);
MOS_AGONDEV_ASSERT_REGISTER(TMR0_DR_H, 0x82);
MOS_AGONDEV_ASSERT_REGISTER(TMR0_RR_H, 0x82);
MOS_AGONDEV_ASSERT_REGISTER(PC_DR, 0x9E);
MOS_AGONDEV_ASSERT_REGISTER(PC_DDR, 0x9F);
MOS_AGONDEV_ASSERT_REGISTER(PC_ALT1, 0xA0);
MOS_AGONDEV_ASSERT_REGISTER(PC_ALT2, 0xA1);
MOS_AGONDEV_ASSERT_REGISTER(PD_DR, 0xA2);
MOS_AGONDEV_ASSERT_REGISTER(PD_DDR, 0xA3);
MOS_AGONDEV_ASSERT_REGISTER(PD_ALT1, 0xA4);
MOS_AGONDEV_ASSERT_REGISTER(PD_ALT2, 0xA5);
MOS_AGONDEV_ASSERT_REGISTER(UART0_BRG_L, 0xC0);
MOS_AGONDEV_ASSERT_REGISTER(UART0_IER, 0xC1);
MOS_AGONDEV_ASSERT_REGISTER(UART0_BRG_H, 0xC1);
MOS_AGONDEV_ASSERT_REGISTER(UART0_FCTL, 0xC2);
MOS_AGONDEV_ASSERT_REGISTER(UART0_LCTL, 0xC3);
MOS_AGONDEV_ASSERT_REGISTER(UART0_MCTL, 0xC4);
MOS_AGONDEV_ASSERT_REGISTER(I2C_CTL, 0xCB);
MOS_AGONDEV_ASSERT_REGISTER(I2C_CCR, 0xCC);
MOS_AGONDEV_ASSERT_REGISTER(UART1_BRG_L, 0xD0);
MOS_AGONDEV_ASSERT_REGISTER(UART1_IER, 0xD1);
MOS_AGONDEV_ASSERT_REGISTER(UART1_BRG_H, 0xD1);
MOS_AGONDEV_ASSERT_REGISTER(UART1_FCTL, 0xD2);
MOS_AGONDEV_ASSERT_REGISTER(UART1_LCTL, 0xD3);
MOS_AGONDEV_ASSERT_REGISTER(UART1_MCTL, 0xD4);
MOS_AGONDEV_ASSERT_REGISTER(CLK_PPD1, 0xDB);

#undef MOS_AGONDEV_ASSERT_REGISTER

#undef TMR0_CTL
#undef TMR0_DR_L
#undef TMR0_RR_L
#undef TMR0_DR_H
#undef TMR0_RR_H
#undef PC_DR
#undef PC_DDR
#undef PC_ALT1
#undef PC_ALT2
#undef PD_DR
#undef PD_DDR
#undef PD_ALT1
#undef PD_ALT2
#undef UART0_BRG_L
#undef UART0_IER
#undef UART0_BRG_H
#undef UART0_FCTL
#undef UART0_LCTL
#undef UART0_MCTL
#undef I2C_CTL
#undef I2C_CCR
#undef UART1_BRG_L
#undef UART1_IER
#undef UART1_BRG_H
#undef UART1_FCTL
#undef UART1_LCTL
#undef UART1_MCTL
#undef CLK_PPD1

#define TMR0_CTL IO(MOS_AGONDEV_ADDR_TMR0_CTL)
#define TMR0_DR_L IO(MOS_AGONDEV_ADDR_TMR0_DR_L)
#define TMR0_RR_L IO(MOS_AGONDEV_ADDR_TMR0_RR_L)
#define TMR0_DR_H IO(MOS_AGONDEV_ADDR_TMR0_DR_H)
#define TMR0_RR_H IO(MOS_AGONDEV_ADDR_TMR0_RR_H)
#define PC_DR IO(MOS_AGONDEV_ADDR_PC_DR)
#define PC_DDR IO(MOS_AGONDEV_ADDR_PC_DDR)
#define PC_ALT1 IO(MOS_AGONDEV_ADDR_PC_ALT1)
#define PC_ALT2 IO(MOS_AGONDEV_ADDR_PC_ALT2)
#define PD_DR IO(MOS_AGONDEV_ADDR_PD_DR)
#define PD_DDR IO(MOS_AGONDEV_ADDR_PD_DDR)
#define PD_ALT1 IO(MOS_AGONDEV_ADDR_PD_ALT1)
#define PD_ALT2 IO(MOS_AGONDEV_ADDR_PD_ALT2)
#define UART0_BRG_L IO(MOS_AGONDEV_ADDR_UART0_BRG_L)
#define UART0_IER IO(MOS_AGONDEV_ADDR_UART0_IER)
#define UART0_BRG_H IO(MOS_AGONDEV_ADDR_UART0_BRG_H)
#define UART0_FCTL IO(MOS_AGONDEV_ADDR_UART0_FCTL)
#define UART0_LCTL IO(MOS_AGONDEV_ADDR_UART0_LCTL)
#define UART0_MCTL IO(MOS_AGONDEV_ADDR_UART0_MCTL)
#define I2C_CTL IO(MOS_AGONDEV_ADDR_I2C_CTL)
#define I2C_CCR IO(MOS_AGONDEV_ADDR_I2C_CCR)
#define UART1_BRG_L IO(MOS_AGONDEV_ADDR_UART1_BRG_L)
#define UART1_IER IO(MOS_AGONDEV_ADDR_UART1_IER)
#define UART1_BRG_H IO(MOS_AGONDEV_ADDR_UART1_BRG_H)
#define UART1_FCTL IO(MOS_AGONDEV_ADDR_UART1_FCTL)
#define UART1_LCTL IO(MOS_AGONDEV_ADDR_UART1_LCTL)
#define UART1_MCTL IO(MOS_AGONDEV_ADDR_UART1_MCTL)
#define CLK_PPD1 IO(MOS_AGONDEV_ADDR_CLK_PPD1)

#define DI() __asm__ volatile ("di" ::: "memory")
#define EI() __asm__ volatile ("ei" ::: "memory")

#endif
