; generated by zds2gas frontend schema 2
; translation unit: fixtures/compatibility.zds.asm
; agon-mos input identity: unversioned-single-file
; expanded input sha256: 492f080b20b434356ea9d681003630c5d26ddbed08a0f6741b97252baabd6688
; DO NOT EDIT: generated build input
.ASSUME ADL = 1
.section .text
.macro zds_WAIT VALUE
.Lzds_m_WAIT_again\@: ld a,\VALUE
jr nz,.Lzds_m_WAIT_again\@
.endm
; zds2gas: SCOPE
entry:
.Lzds_fixtures_compatibility_zds_asm_f4df0446_s001__24_named: zds_WAIT 1
jr .Lzds_fixtures_compatibility_zds_asm_f4df0446_a0001
.Lzds_fixtures_compatibility_zds_asm_f4df0446_a0001: db 0xAA
jr .Lzds_fixtures_compatibility_zds_asm_f4df0446_s001__24_named
; zds2gas: SCOPE
.Lzds_fixtures_compatibility_zds_asm_f4df0446_s002_loop_3f_: djnz .Lzds_fixtures_compatibility_zds_asm_f4df0446_s002_loop_3f_
d32 0x12345678
d24 0xabcdef
; zds2gas: END
